name: Update All-Time WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at 12 AM
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install axios
        run: npm install axios

      - name: Run WakaTime Stats Script
        run: node wakatime-stats.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit & Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "📊 Update WakaTime stats"
          git push
